### ISSUE TITLE
Github action to create encrypted package

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-encrypted-rules#1]
@fukusuket Could I ask you to do this one?
We need to create a github action to copy all of the hayabusa and sigma rules from the hayabusa-rules repository and encrypt and zip them into a `rules.zip` file with a password of `yamato-security-hayabusa`. I think using the standard encryption used in the `zip` utility might be better as we don't need the best encryption and compression that `7z` might offer. We want to prioritize speed and less CPU usage.

**Comment by fukusuket** [comment]
Thank you for comment :) Yes, I would love to implement it!💪

**Comment by YamatoSecurity** [comment]
I just remembered we need to copy the `config` directory as well so the following directories need to be synced:
```
config
hayabusa
sigma
```

**Comment by fukusuket** [comment]
@YamatoSecurity @hitenkoku 
For now, I created an Actions that creates an encrypted zip. (Executing the Actions will commit/push to this repository.)
What do you think? If you see something that needs to be changed, please let me know🙏

(Since this is the first implementation, I committed directly to main, but after this implementation, I will create a PR.)

**Comment by fukusuket** [comment]
https://github.com/Yamato-Security/hayabusa-encrypted-rules/actions/workflows/create-encrypted-package.yml
- It will be executed by cron at 20:30(UTC). Manual execution is also possible.
- If there is no difference since the last execution, do not commit/push.

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much! LGTM! I checked that I could unzip it and the contents look good. I think committing to `main` is fine for now.

**Comment by YamatoSecurity** [comment]
Implemented.
