### ISSUE TITLE
Combine hayabusa-rules `config` files into one file.

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-encrypted-rules#2]
@fukusuket Could I ask you to do this one?
We need to combine all of the config files inside the `config` directory of the hayabusa-rules repository but there are 2 problems: 1) Not all files are YAML files and 2) There are sub-directories.

I was thinking about putting all the files into a single `.yaml` file in a similar way we create `encoded_rules.yml` but due to these problems it might be difficult? If so, maybe we can compress them into an un-encrypted `.zip` file and just load the files from the zip file?

What do you think?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Yes, I agree with the idea of zipping it into one file!!  The disadvantage is that unzipping is required each time, but I think it is not a problem :) I would love to implement it!💪

**Comment by fukusuket** [comment]
There seems to be some configuration files that are not currently in use, so I will delete them as well. If you have any unused configuration files, we would appreciate it if you could let me know🙏

**Comment by fukusuket** [comment]
@YamatoSecurity 
The following files are not referenced by the program. Do we need to leave these txts? 🤔
- rules/config/regex/LOLBAS_commands.txt
- rules/config/regex/LOLBAS_paths.txt
- rules/config/regex/record_data_filter.txt
- rules/config/statistics_event_info.txt

**Comment by fukusuket** [comment]
memo:
Only the following rules use `allowlist`/`regexes`
- https://github.com/Yamato-Security/hayabusa-rules?tab=readme-ov-file#regexes-and-allowlist-keywords
- https://github.com/Yamato-Security/hayabusa-rules/blob/28fdd691e7cf4e9bdcb53dfa2b947ee268e57b75/hayabusa/builtin/System/Sys_7045_High_ServiceInstalled_PossiblyMaliciousSvcInstalled.yml#L9

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks for looking this up. I'll try to add the regex inside the rule so we can deprecate external file use and reduce the amount of files.
